Repository msgpack/msgpack-javascript, pull requests merged in 2019-05, with the labels that each got.

#43 support whatwg-stream.ReadableStream as decodeAsync() input source
  src/decodeAsync.ts
  src/utils/stream.ts
  test/readme.test.ts
  test/whatwg-streams.test.ts
Labels: Feature

#45 Export Decoder and Encoder for direct usage
  src/index.ts
Labels: Feature

#44 Add basic tests for decodeArrayStream
  test/decodeArrayStream.test.ts
Labels: Tests

#46 Add decodeStream
  src/Decoder.ts
  src/decodeAsync.ts
  test/decodeStream.test.ts
Labels: Feature

#51 simplify type of decode()'s first arg; ArrayLike<number> includes Uint8Array, anyway
  README.md
  src/Decoder.ts
  src/decode.ts
  src/decodeAsync.ts
Labels: Docs

#52 decodeStream() is missing in export list in src/index.ts
  src/index.ts
  test/decodeStream.test.ts
Labels: Bugfix
